### ISSUE TITLE
The regular expression could be simplified

### ISSUE THREAD

**Issue by bronium** [smillepack/advent_of_code#1]
https://github.com/smillepack/advent_of_code/blob/ccaab4e1b3cc97051789133ea5f8137f1a9dba81/2024/14_1.js#L12

Suggestion: 
```js
const [pX, pY, vX, vY] = input.match(/-?\d+/g); 
```

**Comment by ak-krivonosov** [comment]
Good catch. Your contribution is highly appreciated. Currently one of our best dev is working to resolve it. I’m afraid I’ll have to ask you to review the PR
